
-------------------------------------------------------------------------------------------






[Train] Epoch: 1/5: 100%|██████████| 656/656 [00:14<00:00, 45.35batch/s, accuracy=0.981, loss=0.155]
Traceback (most recent call last):
  File "C:/Users/Choo/PycharmProjects/Gwangggi/Week1/simpleCNN.py", line 96, in <module>
    save_checkpoint(model, f'best_model/[ep{best_epoch}_{best_accuracy:0.6f}].pth')
  File "C:/Users/Choo/PycharmProjects/Gwangggi/Week1/simpleCNN.py", line 52, in save_checkpoint
    torch.save(model, filename)
  File "C:\Users\Choo\anaconda3\envs\gwangggi\lib\site-packages\torch\serialization.py", line 376, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "C:\Users\Choo\anaconda3\envs\gwangggi\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\Choo\anaconda3\envs\gwangggi\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'best_model/[ep1_0.981373].pth'